// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file GameMessage.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen.
 */

#ifndef FAST_DDS_GENERATED__GAMEMESSAGE_HPP
#define FAST_DDS_GENERATED__GAMEMESSAGE_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(GAMEMESSAGE_SOURCE)
#define GAMEMESSAGE_DllAPI __declspec( dllexport )
#else
#define GAMEMESSAGE_DllAPI __declspec( dllimport )
#endif // GAMEMESSAGE_SOURCE
#else
#define GAMEMESSAGE_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define GAMEMESSAGE_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure GameMessage defined by the user in the IDL file.
 * @ingroup GameMessage
 */
class GameMessage
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport GameMessage()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~GameMessage()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object GameMessage that will be copied.
     */
    eProsima_user_DllExport GameMessage(
            const GameMessage& x)
    {
                    m_index = x.m_index;

                    m_game_id = x.m_game_id;

                    m_uid = x.m_uid;

                    m_username = x.m_username;

                    m_rps = x.m_rps;

                    m_ttt = x.m_ttt;

                    m_c4 = x.m_c4;

                    m_chess_from = x.m_chess_from;

                    m_chess_to = x.m_chess_to;

                    m_chess_prom = x.m_chess_prom;

                    m_message = x.m_message;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object GameMessage that will be copied.
     */
    eProsima_user_DllExport GameMessage(
            GameMessage&& x) noexcept
    {
        m_index = x.m_index;
        m_game_id = x.m_game_id;
        m_uid = std::move(x.m_uid);
        m_username = std::move(x.m_username);
        m_rps = x.m_rps;
        m_ttt = x.m_ttt;
        m_c4 = x.m_c4;
        m_chess_from = x.m_chess_from;
        m_chess_to = x.m_chess_to;
        m_chess_prom = x.m_chess_prom;
        m_message = std::move(x.m_message);
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object GameMessage that will be copied.
     */
    eProsima_user_DllExport GameMessage& operator =(
            const GameMessage& x)
    {

                    m_index = x.m_index;

                    m_game_id = x.m_game_id;

                    m_uid = x.m_uid;

                    m_username = x.m_username;

                    m_rps = x.m_rps;

                    m_ttt = x.m_ttt;

                    m_c4 = x.m_c4;

                    m_chess_from = x.m_chess_from;

                    m_chess_to = x.m_chess_to;

                    m_chess_prom = x.m_chess_prom;

                    m_message = x.m_message;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object GameMessage that will be copied.
     */
    eProsima_user_DllExport GameMessage& operator =(
            GameMessage&& x) noexcept
    {

        m_index = x.m_index;
        m_game_id = x.m_game_id;
        m_uid = std::move(x.m_uid);
        m_username = std::move(x.m_username);
        m_rps = x.m_rps;
        m_ttt = x.m_ttt;
        m_c4 = x.m_c4;
        m_chess_from = x.m_chess_from;
        m_chess_to = x.m_chess_to;
        m_chess_prom = x.m_chess_prom;
        m_message = std::move(x.m_message);
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x GameMessage object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const GameMessage& x) const
    {
        return (m_index == x.m_index &&
           m_game_id == x.m_game_id &&
           m_uid == x.m_uid &&
           m_username == x.m_username &&
           m_rps == x.m_rps &&
           m_ttt == x.m_ttt &&
           m_c4 == x.m_c4 &&
           m_chess_from == x.m_chess_from &&
           m_chess_to == x.m_chess_to &&
           m_chess_prom == x.m_chess_prom &&
           m_message == x.m_message);
    }

    /*!
     * @brief Comparison operator.
     * @param x GameMessage object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const GameMessage& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function sets a value in member index
     * @param _index New value for member index
     */
    eProsima_user_DllExport void index(
            uint32_t _index)
    {
        m_index = _index;
    }

    /*!
     * @brief This function returns the value of member index
     * @return Value of member index
     */
    eProsima_user_DllExport uint32_t index() const
    {
        return m_index;
    }

    /*!
     * @brief This function returns a reference to member index
     * @return Reference to member index
     */
    eProsima_user_DllExport uint32_t& index()
    {
        return m_index;
    }


    /*!
     * @brief This function sets a value in member game_id
     * @param _game_id New value for member game_id
     */
    eProsima_user_DllExport void game_id(
            uint8_t _game_id)
    {
        m_game_id = _game_id;
    }

    /*!
     * @brief This function returns the value of member game_id
     * @return Value of member game_id
     */
    eProsima_user_DllExport uint8_t game_id() const
    {
        return m_game_id;
    }

    /*!
     * @brief This function returns a reference to member game_id
     * @return Reference to member game_id
     */
    eProsima_user_DllExport uint8_t& game_id()
    {
        return m_game_id;
    }


    /*!
     * @brief This function copies the value in member uid
     * @param _uid New value to be copied in member uid
     */
    eProsima_user_DllExport void uid(
            const std::string& _uid)
    {
        m_uid = _uid;
    }

    /*!
     * @brief This function moves the value in member uid
     * @param _uid New value to be moved in member uid
     */
    eProsima_user_DllExport void uid(
            std::string&& _uid)
    {
        m_uid = std::move(_uid);
    }

    /*!
     * @brief This function returns a constant reference to member uid
     * @return Constant reference to member uid
     */
    eProsima_user_DllExport const std::string& uid() const
    {
        return m_uid;
    }

    /*!
     * @brief This function returns a reference to member uid
     * @return Reference to member uid
     */
    eProsima_user_DllExport std::string& uid()
    {
        return m_uid;
    }


    /*!
     * @brief This function copies the value in member username
     * @param _username New value to be copied in member username
     */
    eProsima_user_DllExport void username(
            const std::string& _username)
    {
        m_username = _username;
    }

    /*!
     * @brief This function moves the value in member username
     * @param _username New value to be moved in member username
     */
    eProsima_user_DllExport void username(
            std::string&& _username)
    {
        m_username = std::move(_username);
    }

    /*!
     * @brief This function returns a constant reference to member username
     * @return Constant reference to member username
     */
    eProsima_user_DllExport const std::string& username() const
    {
        return m_username;
    }

    /*!
     * @brief This function returns a reference to member username
     * @return Reference to member username
     */
    eProsima_user_DllExport std::string& username()
    {
        return m_username;
    }


    /*!
     * @brief This function sets a value in member rps
     * @param _rps New value for member rps
     */
    eProsima_user_DllExport void rps(
            uint8_t _rps)
    {
        m_rps = _rps;
    }

    /*!
     * @brief This function returns the value of member rps
     * @return Value of member rps
     */
    eProsima_user_DllExport uint8_t rps() const
    {
        return m_rps;
    }

    /*!
     * @brief This function returns a reference to member rps
     * @return Reference to member rps
     */
    eProsima_user_DllExport uint8_t& rps()
    {
        return m_rps;
    }


    /*!
     * @brief This function sets a value in member ttt
     * @param _ttt New value for member ttt
     */
    eProsima_user_DllExport void ttt(
            uint32_t _ttt)
    {
        m_ttt = _ttt;
    }

    /*!
     * @brief This function returns the value of member ttt
     * @return Value of member ttt
     */
    eProsima_user_DllExport uint32_t ttt() const
    {
        return m_ttt;
    }

    /*!
     * @brief This function returns a reference to member ttt
     * @return Reference to member ttt
     */
    eProsima_user_DllExport uint32_t& ttt()
    {
        return m_ttt;
    }


    /*!
     * @brief This function sets a value in member c4
     * @param _c4 New value for member c4
     */
    eProsima_user_DllExport void c4(
            uint64_t _c4)
    {
        m_c4 = _c4;
    }

    /*!
     * @brief This function returns the value of member c4
     * @return Value of member c4
     */
    eProsima_user_DllExport uint64_t c4() const
    {
        return m_c4;
    }

    /*!
     * @brief This function returns a reference to member c4
     * @return Reference to member c4
     */
    eProsima_user_DllExport uint64_t& c4()
    {
        return m_c4;
    }


    /*!
     * @brief This function sets a value in member chess_from
     * @param _chess_from New value for member chess_from
     */
    eProsima_user_DllExport void chess_from(
            uint8_t _chess_from)
    {
        m_chess_from = _chess_from;
    }

    /*!
     * @brief This function returns the value of member chess_from
     * @return Value of member chess_from
     */
    eProsima_user_DllExport uint8_t chess_from() const
    {
        return m_chess_from;
    }

    /*!
     * @brief This function returns a reference to member chess_from
     * @return Reference to member chess_from
     */
    eProsima_user_DllExport uint8_t& chess_from()
    {
        return m_chess_from;
    }


    /*!
     * @brief This function sets a value in member chess_to
     * @param _chess_to New value for member chess_to
     */
    eProsima_user_DllExport void chess_to(
            uint8_t _chess_to)
    {
        m_chess_to = _chess_to;
    }

    /*!
     * @brief This function returns the value of member chess_to
     * @return Value of member chess_to
     */
    eProsima_user_DllExport uint8_t chess_to() const
    {
        return m_chess_to;
    }

    /*!
     * @brief This function returns a reference to member chess_to
     * @return Reference to member chess_to
     */
    eProsima_user_DllExport uint8_t& chess_to()
    {
        return m_chess_to;
    }


    /*!
     * @brief This function sets a value in member chess_prom
     * @param _chess_prom New value for member chess_prom
     */
    eProsima_user_DllExport void chess_prom(
            uint8_t _chess_prom)
    {
        m_chess_prom = _chess_prom;
    }

    /*!
     * @brief This function returns the value of member chess_prom
     * @return Value of member chess_prom
     */
    eProsima_user_DllExport uint8_t chess_prom() const
    {
        return m_chess_prom;
    }

    /*!
     * @brief This function returns a reference to member chess_prom
     * @return Reference to member chess_prom
     */
    eProsima_user_DllExport uint8_t& chess_prom()
    {
        return m_chess_prom;
    }


    /*!
     * @brief This function copies the value in member message
     * @param _message New value to be copied in member message
     */
    eProsima_user_DllExport void message(
            const std::string& _message)
    {
        m_message = _message;
    }

    /*!
     * @brief This function moves the value in member message
     * @param _message New value to be moved in member message
     */
    eProsima_user_DllExport void message(
            std::string&& _message)
    {
        m_message = std::move(_message);
    }

    /*!
     * @brief This function returns a constant reference to member message
     * @return Constant reference to member message
     */
    eProsima_user_DllExport const std::string& message() const
    {
        return m_message;
    }

    /*!
     * @brief This function returns a reference to member message
     * @return Reference to member message
     */
    eProsima_user_DllExport std::string& message()
    {
        return m_message;
    }



private:

    uint32_t m_index{0};
    uint8_t m_game_id{0};
    std::string m_uid;
    std::string m_username;
    uint8_t m_rps{0};
    uint32_t m_ttt{0};
    uint64_t m_c4{0};
    uint8_t m_chess_from{0};
    uint8_t m_chess_to{0};
    uint8_t m_chess_prom{0};
    std::string m_message;

};

#endif // _FAST_DDS_GENERATED_GAMEMESSAGE_HPP_


