struct Game {
    unsigned long game_id; // 0: rps, 1: ttt, ...

    string uid; // user id
    string oid; // opp id

    unsigned long ngames; // number of games played
    unsigned long wins; // wins

    unsigned long rps; // rock paper scissors game state
    unsigned long ttt; // tic-tac-toe game state
    unsigned long c4; // connect 4 game state

    string message;
};