struct GameMessage {
    long game_id; // 0: rps, 1: ttt, ...

    string uid; // user id
    string oid; // opp id

    long ngames; // number of games played
    long wins; // wins

    long rps; // rock paper scissors game state
    long ttt; // tic-tac-toe game state
    long c4; // connect 4 game state

    string message;
};